version: '3.4'
services:

  nginx:
    image: nginx:latest
    container_name: bottle-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bottle
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  bottle:
    image: ghcr.io/garutilorenzo/bottle-be:dev
    container_name: bottle
    environment:
      - PATH=$PATH:/app/.local/bin/
      - PYTHONPATH=$PYTHONPATH:/app/src
      - BOTTLE_APP_ENVIRONMENT=prod
      - BOTTLE_APP_NAME=bottle
    volumes:
      - ./src:/app/src
      - ./data:/data
    command: ['uwsgi', '--ini', 'bottle/uwsgi.ini']
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  pgsql:
    image: postgres:latest
    container_name: postgres
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
      #- ./sql:/docker-entrypoint-initdb.d
    command: -c shared_buffers=1536MB -c work_mem=15MB
    environment:
      - POSTGRES_PASSWORD=b0tTl3_Be#
      - POSTGRES_USER=bottle
      - POSTGRES_DB=bottle_exchange
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bottle"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  redis:
    image: redis:6-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

volumes:
  postgres: